export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOADED_CITIES = "LOADED_CITIES"
export const ADD_CITY = "ADD_CITY"
export const CITY_LOADING = "CITY_LOADING"
export const CITY_ERROR = "CITY_ERROR"

export const LOADED_LOCATIONS = "LOADED_LOCATIONS"
export const ADD_LOCATION = "ADD_LOCATION"
export const LOCATION_LOADING = "LOCATION_LOADING"
export const LOCATION_ERROR = "LOCATION_ERROR"

export const LOADED_SEMESTERS = "LOADED_SEMESTERS"
export const ADD_SEMESTER = "ADD_SEMESTER"
export const SEMESTER_LOADING = "SEMESTER_LOADING"
export const SEMESTER_ERROR = "SEMESTER_ERROR"

export const LOADED_PICKUPPOINTS = "LOADED_PICKUPPOINTS"
export const ADD_PICKUPPOINTS = "ADD_PICKUPPOINTS"
export const PICKUPPOINTS_LOADING = "PICKUPPOINTS_LOADING"
export const PICKUPPOINTS_ERROR = "PICKUPPOINTS_ERROR"
